@extends('layout.layout')

@section('content')
<div class="container-fluid py-4">
    <!-- Header Section -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h2 class="fw-bold text-primary"><i class="bi bi-tools me-2"></i>Tra cứu lỗi kỹ thuật</h2>
                    <p class="text-muted mb-0">Hệ thống tra cứu tài liệu sửa chữa dành cho kỹ thuật viên</p>
                </div>
                <div>
                    <a href="{{ route('warranty.document.create') }}" class="btn btn-primary btn-sm me-2">
                        <i class="bi bi-plus-lg me-1"></i>Thêm mới
                    </a>
                    <button class="btn btn-outline-secondary btn-sm" onclick="location.reload()">
                        <i class="bi bi-arrow-clockwise me-1"></i>Làm mới
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Search/Filter Section -->
    <div class="card border-0 shadow-sm mb-4" style="border-radius: 15px;">
        <div class="card-body p-4">
            <div class="row g-3">
                <!-- 1. Danh mục -->
                <div class="col-md-3">
                    <label class="form-label fw-semibold text-secondary">Danh mục sản phẩm</label>
                    <select class="form-select" id="categorySelect">
                        <option selected disabled>-- Chọn danh mục --</option>
                        @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name_vi }}</option>
                        @endforeach
                    </select>
                </div>
                
                <!-- 2. Sản phẩm (Tên/Loại) -->
                <div class="col-md-3">
                    <label class="form-label fw-semibold text-secondary">Sản phẩm</label>
                    <select class="form-select" id="productNameSelect">
                        <option selected disabled>-- Chọn sản phẩm --</option>
                    </select>
                </div>

                <!-- 3. Xuất xứ -->
                <div class="col-md-3">
                    <label class="form-label fw-semibold text-secondary">Xuất xứ</label>
                    <select class="form-select" id="originSelect" disabled>
                        <option selected disabled>-- Chọn xuất xứ --</option>
                    </select>
                </div>

                <!-- 4. Mã sản phẩm -->
                <div class="col-md-3">
                    <label class="form-label fw-semibold text-secondary">Mã sản phẩm</label>
                    <div class="input-group">
                        <select class="form-select" id="productCodeSelect" disabled>
                            <option selected disabled>-- Chọn mã SP --</option>
                        </select>
                        <button class="btn btn-primary" type="button" id="btnSearch" disabled>
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Results Section (Initially Hidden) -->
    <div id="resultsSection" style="display: none;">
        <h5 class="mb-3 fw-bold text-dark border-start border-4 border-primary ps-3">Danh sách mã lỗi thường gặp</h5>
        
        <div class="row g-4" id="errorGrid">
            <!-- Example Item Generated by JS -->
        </div>

        <!-- Empty State -->
        <div id="emptyState" class="text-center py-5 d-none">
            <img src="https://cdn-icons-png.flaticon.com/512/7486/7486777.png" alt="No data" style="width: 100px; opacity: 0.5;">
            <p class="text-muted mt-3">Không tìm thấy dữ liệu phù hợp.</p>
        </div>
    </div>
</div>

<!-- Detailed Modal (No Changes needed) -->
<div class="modal fade" id="errorDetailModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content border-0 shadow-lg" style="border-radius: 15px; overflow: hidden;">
            <div class="modal-header bg-primary text-white py-3">
                <h5 class="modal-title fw-bold" id="detailModalTitle">Chi tiết lỗi</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <div class="row g-0 h-100">
                    <!-- Left Side: Description & Solution -->
                    <div class="col-lg-7 p-4 border-end">
                        <div class="mb-4">
                            <span class="badge bg-danger rounded-pill mb-2 px-3 py-2" id="detailErrorCode">E-01</span>
                            <h3 class="fw-bold text-dark mb-3" id="detailErrorName">Lỗi cảm biến LIDAR</h3>
                            
                            <div class="alert alert-light border-start border-4 border-warning bg-light-warning">
                                <h6 class="fw-bold text-warning mb-1"><i class="bi bi-exclamation-triangle-fill me-2"></i>Mô tả hiện tượng</h6>
                                <p class="mb-0 text-secondary" id="detailDescription">Robot khởi động nhưng quay tại chỗ, báo lỗi Lidar bị kẹt hoặc không quay.</p>
                            </div>
                        </div>

                        <div class="card border-0 bg-light rounded-3 mb-4">
                            <div class="card-body">
                                <h5 class="fw-bold text-success mb-3"><i class="bi bi-wrench-adjustable-circle-fill me-2"></i>Hướng dẫn xử lý</h5>
                                <div id="detailSolution" class="tech-steps">
                                    <!-- Steps content -->
                                </div>
                            </div>
                        </div>

                        <div>
                            <h6 class="fw-bold text-secondary mb-3"><i class="bi bi-file-earmark-pdf-fill me-2"></i>Tài liệu tham khảo</h6>
                            <div class="list-group list-group-flush" id="detailDocuments">
                                <!-- Docs content -->
                            </div>
                        </div>
                    </div>

                    <!-- Right Side: Media -->
                    <div class="col-lg-5 bg-light p-4">
                        <h6 class="fw-bold text-secondary mb-3"><i class="bi bi-images me-2"></i>Hình ảnh / Video minh họa</h6>
                        
                        <div id="mediaCarousel" class="carousel slide rounded-3 overflow-hidden shadow-sm mb-3" data-bs-ride="carousel">
                            <div class="carousel-inner" id="detailMediaInner">
                                <!-- Slides -->
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#mediaCarousel" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#mediaCarousel" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                        
                        <div class="d-grid gap-2">
                            <a href="#" class="btn btn-outline-primary" id="btnDownloadAll">
                                <i class="bi bi-cloud-arrow-down-fill me-2"></i>Tải xuống toàn bộ tài liệu
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="{{ asset('css/technicaldocument/index.css') }}">

<script>
    window.technicalDocumentIndexConfig = {
        routes: {
            getProductsByCategory: "{{ route('warranty.document.getProductsByCategory') }}",
            getOriginsByProduct: "{{ route('warranty.document.getOriginsByProduct') }}",
            getModelsByOrigin: "{{ route('warranty.document.getModelsByOrigin') }}"
        }
    };
</script>
<script src="{{ asset('js/technicaldocument/index.js') }}"></script>
@endsection

